from ._api import (
    EmbeddingPreprocessor as EmbeddingPreprocessor,
    FitStats as FitStats,
    WhitenModel as WhitenModel,
    cosine_similarity as cosine_similarity,
    l2_normalize_rows as l2_normalize_rows,
    mean_center as mean_center,
    standardize_columns as standardize_columns,
    whiten_pca as whiten_pca,
    remove_top_principal_components as remove_top_principal_components,
    cosine_similarity_matrix as cosine_similarity_matrix,
    cosine_similarity_matrix_stats as cosine_similarity_matrix_stats,
    pearson_correlation as pearson_correlation,
    spearman_correlation as spearman_correlation,
    adjusted_rand_index as adjusted_rand_index,
    normalized_mutual_info as normalized_mutual_info,
    purity_score as purity_score,
    calinski_harabasz_score as calinski_harabasz_score,
    silhouette_score as silhouette_score,
    effective_rank as effective_rank,
    similarity_to_global_mean as similarity_to_global_mean,
    compute_hubness as compute_hubness,
    trustworthiness as trustworthiness,
    continuity as continuity,
    recall_at_k as recall_at_k,
    precision_at_k as precision_at_k,
    mean_reciprocal_rank as mean_reciprocal_rank,
    ndcg_at_k as ndcg_at_k,
    coverage_at_k as coverage_at_k,
)
from ._errors import NlpieError as NlpieError, PreprocessingError as PreprocessingError
from .interpret import HubnessExplanation as HubnessExplanation, HubInfo as HubInfo, explain_hubness as explain_hubness
from .backends import PlotBackend as PlotBackend, PlotlyBackend as PlotlyBackend
from .dashboard import (
    plot_hubness_histogram as plot_hubness_histogram,
    plot_similarity_distribution as plot_similarity_distribution,
    plot_similarity_to_mean as plot_similarity_to_mean,
    plot_projection_quality as plot_projection_quality,
    plot_retrieval_metrics as plot_retrieval_metrics,
    plot_quality_report as plot_quality_report,
)
