import numpy as np
from typing import Optional

class FitStats:
    mean: list[float]
    std: Optional[list[float]]

class WhitenModel:
    mean: list[float]
    projection: list[list[float]]
    eigenvalues: list[float]
    eps: float

class EmbeddingPreprocessor:
    def __init__(self, eps: Optional[float] = None) -> None: ...
    def l2_normalize_rows(self, embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]]) -> list[list[float]]: ...
    def mean_center(self, embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]]) -> tuple[list[list[float]], FitStats]: ...
    def standardize_columns(self, embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]]) -> tuple[list[list[float]], FitStats]: ...
    def whiten_pca(self, embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]], n_components: Optional[int] = None) -> tuple[list[list[float]], WhitenModel]: ...
    def remove_top_principal_components(self, embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]], n_components: int) -> list[list[float]]: ...

def cosine_similarity(lhs: list[float], rhs: list[float]) -> float: ...
def l2_normalize_rows(embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]], eps: float = 1e-12) -> list[list[float]]: ...
def mean_center(embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]]) -> tuple[list[list[float]], FitStats]: ...
def standardize_columns(embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]], eps: float = 1e-12) -> tuple[list[list[float]], FitStats]: ...
def whiten_pca(embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]], n_components: Optional[int] = None, eps: float = 1e-12) -> tuple[list[list[float]], WhitenModel]: ...
def remove_top_principal_components(embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]], n_components: int) -> list[list[float]]: ...

def cosine_similarity_matrix(embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]], eps: float = 1e-12) -> list[list[float]]: ...
def pearson_correlation(x: list[float], y: list[float]) -> float: ...
def spearman_correlation(x: list[float], y: list[float]) -> float: ...

def adjusted_rand_index(labels_true: list[int], labels_pred: list[int]) -> float: ...
def normalized_mutual_info(labels_true: list[int], labels_pred: list[int]) -> float: ...
def purity_score(labels_true: list[int], labels_pred: list[int]) -> float: ...
def calinski_harabasz_score(embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]], labels: list[int]) -> float: ...
def silhouette_score(embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]], labels: list[int]) -> float: ...

def effective_rank(embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]]) -> float: ...
def similarity_to_global_mean(embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]]) -> list[float]: ...
def compute_hubness(embeddings: np.ndarray[tuple[int, int], np.dtype[np.float32]], k: int = 5) -> tuple[list[int], float]: ...

def trustworthiness(high_dim: np.ndarray[tuple[int, int], np.dtype[np.float32]], low_dim: np.ndarray[tuple[int, int], np.dtype[np.float32]], k: int = 10) -> float: ...
def continuity(high_dim: np.ndarray[tuple[int, int], np.dtype[np.float32]], low_dim: np.ndarray[tuple[int, int], np.dtype[np.float32]], k: int = 10) -> float: ...

def recall_at_k(retrieved: list[int], relevant: list[int], k: int) -> float: ...
def precision_at_k(retrieved: list[int], relevant: list[int], k: int) -> float: ...
def mean_reciprocal_rank(retrieved: list[int], relevant: list[int]) -> float: ...
def ndcg_at_k(retrieved: list[int], relevant: list[int], k: int) -> float: ...
def coverage_at_k(all_retrieved: list[list[int]], all_relevant: list[list[int]], k: int) -> float: ...
